"""Single point of contact with the OpenAI API."""

from openai import OpenAI, OpenAIError

from src.config import MAX_TOKENS, MODEL, OPENAI_API_KEY, TEMPERATURE

if not OPENAI_API_KEY:
    raise RuntimeError(
        "OPENAI_API_KEY is missing. Copy .env.example to .env and fill in the key."
    )

client = OpenAI(api_key=OPENAI_API_KEY)


def create_chat_completion(messages: list[dict[str, str]]) -> str:
    """
    Create a chat completion using the configured model.

    Args:
        messages (list): A list of message dictionaries, where each message
                         has a role and its content.

    Returns:
        str: The response generated by the model.

    Raises:
        RuntimeError: If the API call fails (network, rate limit, auth, etc.).
    """
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=messages,
            temperature=TEMPERATURE,
            max_completion_tokens=MAX_TOKENS,
        )
    except OpenAIError as error:
        raise RuntimeError(f"OpenAI API call failed: {error}") from error

    return response.choices[0].message.content
